config/routes.rb
Rails.application.routes.draw do

  get 'users/:id/followees', to: "users#followees", as: "followee"
  get 'users/:id/followers', to: "users#followers", as: "follower"
  
  resources :users, except: :destroy
  
  post 'users/:id', to: "users#follow", as: "follow"
  delete 'users/:id/edit', to: "users#destroy", as: "destroy"
  delete 'users/:id', to: "users#unfollow", as: "unfollow"

  resources :tweets, only: [:index, :new, :create, :destroy]
  resources :likes
  



  delete 'tweets/:id', to: "tweets#destroy", as: "delete_tweet"
  delete 'tweets/:id/show', to: "tweets#delete_this", as: "delete_this"
 
  get "/tweets/:id", to: "tweets#show", as: "show_tweet"
  get "/", to: "homepage#home", as: "homepage" #show page 
  get "/login", to: "sessions#login" #new 
  post "/login", to: "sessions#process_login" #create
  delete "/logout", to: "sessions#logout", as: "logout" #new 
  get '/trends', to: "tweets#trends", as: "trends"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: 'User'
    belongs_to :followee, class_name: 'User'

end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :tweet
    belongs_to :user


end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes
    validates :text, length: { in: 1..150 }

    def self.sorted_tweets
        Tweet.all.sort_by do |tweet|
            tweet.created_at
        end
    end

    def like_user_ids
        self.likes.map do |like|
            like.user_id
        end
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets
    has_many :likes
    has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
    has_many :followees, through: :followed_users
   
    has_many :following_users, foreign_key: :followee_id, class_name: 'Follow' 
    has_many :followers, through: :following_users
   
    validates :name, presence: true
    validates :password, length: { in: 6..15 }
    validates :handle, length: { in: 3..15 }
    validates :birthday, presence: true

    def twitter_handle
        new_handle = self.handle.split(" ").join
        "@#{new_handle}"
    end
    
  
    def feed
    feed = []
    self.followees.each do |followee|
      followee.tweets.each do |tweet|
       feed << tweet
      end
    end
    self.tweets.each do |tweet|
        feed << tweet
    end
    feed.sort_by(&:created_at).reverse
  end
    
    


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    
    
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
      
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController


  def home
    render :home
  end

  


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_user_session

  def index
    
  end

  def show

  end

  def new
    @like = Like.new
  end

  def create
    #params[:like][:user_id, :tweet_id]
    #   Like.create(user_id: .id, tweet_id: tweet.id)
    
    @like = Like.create(user_id: @username["id"], tweet_id: Tweet.find(params[:format]).id)
    #byebug
    redirect_back(fallback_location:"/")

    #@like = Like.create(like_params)

  end

  def destroy

    @tweet= Tweet.find(params[:id])
    @like = Like.find_by(user_id: @username["id"], tweet_id: @tweet.id)
    #Tweet.find(params[:format]).id)
    @like.destroy
    redirect_back(fallback_location:"/")
  end


  private
  def like_params
    params.require(:like).permit(:user_id, :tweet_id)
  end

  def set_user_session
    @username = session[:user]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  
  def login
  end
  
  def logout
    session.clear
    redirect_to homepage_path
  end

  def process_login
  
    session[:user] = User.find_by(name: params[:name])
    @user = session[:user]
    
    if @user && @user.password == params[:password]
        redirect_to tweets_path
      else
        render :login
      end

  end




end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_user_session
  def index
    @tweets = Tweet.all 
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    text = params[:tweet][:text]
    @tweet = Tweet.create(text: text,user_id: @username["id"])

    if @tweet.valid?
      @tweet.save
      redirect_back(fallback_location:"/")
    else
      render :new
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @user = @tweet.user 
    @tweet.destroy
    redirect_back(fallback_location:"/")
  end

  def delete_this
    @tweet = Tweet.find(params[:id])
    @user = @tweet.user 
    @tweet.destroy
    redirect_to tweets_path
  end

  def trends
    @tweets =  Tweet.all
    @tweets.sample
  end

  private

  def tweet_params
    params.require(:tweet).permit(:text)
  end

  def set_user_session
    @username = session[:user]

    @current_user=User.find_by(id: @username['id'])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user_session, except: [:new, :create]

  def index
    @users = User.all 
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
  
    @user = User.create(user_params)
    session[:user] = @user

    if @user.valid?
      @user.save
    redirect_to tweets_path
    else
      render :new
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    #@current_user.destroy
    #@current_user.tweets.clear
    


    @user = User.find(params[:id])
    # byebug
    @user.destroy
    # byebug
    @user.tweets.clear
    redirect_to homepage_path
  end

  def followees
    @user = User.find(params[:id])
    @followees = @user.followees.uniq
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.uniq
  end

  def follow
    #Follow.create(follower_id: @user.id, followee_id: @username["id"])
    @user = User.find(params[:id])
    # @im_following << @user
    #byebug
    @current_user.followees << @user
    @current_user.save
    redirect_back(fallback_location:"/")
  end

  def unfollow
    @user = User.find(params[:id])
    # @im_following.delete(@user.id)
    @current_user.followees.delete(@user)
    @current_user.save
    redirect_back(fallback_location:"/")
    
  end

  private
  
  def user_params
    params.require(:user).permit(:name,:password,:handle,:bio,:birthday)
  end

  def set_user_session
    @username = session[:user]

    @current_user=User.find_by(id: @username['id'])

  
    # followees_objects = Follow.where(follower_id: @username["id"] )
    #  @im_following = followees_objects.map{ |followees| followees.followee_id}

    # followers_objects = Follow.where(followee_id: @username["id"] )
    # @my_followers = followers_objects.map{ |followers| followers.follower_id}
     

  end



end




# 
# 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follows/create.html.erb
<h1>Follows#create</h1>
<p>Find me in app/views/follows/create.html.erb</p>

app/views/follows/destroy.html.erb
<h1>Follows#destroy</h1>
<p>Find me in app/views/follows/destroy.html.erb</p>

app/views/follows/followee.html.erb
<h1>Follows#followee</h1>
<p>Find me in app/views/follows/followee.html.erb</p>

app/views/follows/follower.html.erb
<h1>Follows#follower</h1>
<p>Find me in app/views/follows/follower.html.erb</p>

app/views/follows/new.html.erb
<h1>Follows#new</h1>
<p>Find me in app/views/follows/new.html.erb</p>

app/views/homepage/home.html.erb
<div class=center>
<br>
<button class="ui white button">
<%= link_to "Login", login_path %> <br>
</button><br><br>


<button class="ui white button">

<%= link_to "Create a New Account", new_user_path, method: :get %>
</button>
</div>
<div style="background-color: #3399FF;">
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
  </head>
  <style>
  .sidenav {
  height: 100%; 
  width: 150px; 
  position: fixed; 
  z-index: 1; 
  top: 0; 
  left: 0;
  background-color: #3399FF; 
  overflow-x: hidden; 
  padding-top: 45px;
}
.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #FFFFFF;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.header {
  text-align: right;
}

.center {
  text-align: center;
}
.right {
  text-align: right;
}

.left {
  text-align: left;
}

.column {
  float: right;
  width: 33.33%;
}

.row:after
 {
  content: "";
  display: table;
  clear: both;
}

.card {
    box-shadow: 0 2px 8px 0 rgba(0, 0, 0, 0.2);
    padding: 15px;
    margin: 7%;
    text-align: center;
    background-color: #f1f1f1;
  }


</style>

  <body>


  <% if @current_user %>
<div class="sidenav">
<a href="/tweets"><i class="home icon"> </i></a>
<a href="/users"><i class="at icon"></i></a>
<a href="/users/<%= @current_user.id%>"><i class="user icon"></i></a>
<a href="/users/<%= @current_user.id%>/edit"><i class="cog icon"></i></a>
</div>
 <% end %>
 <div style="background-color: #3399FF;">
 <div class="header">
 <%= link_to logout_path, method: :delete, class: "navbar-item" do %>
   <b  style= "color: white">Logout</b>
 <% end %>
 </div>
  <div class=center>
      <% if @current_user %>
      <b class="navbar-brand">
       <b style= "color: white"><i class="large twitter square icon"></i></b>
       </div>
       </div>
       
       <% else %>
  <div class=center>
  <b class="navbar-brand">
  <b style= "color: white"><i class="massive twitter square icon"></i></b>
</div>
      
      <%end%>
 

    <%= yield %>
  </body>
</html>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/shared/_header.html.erb
<div class="header" >
<% if session[:user_id]

app/views/tweets/index.html.erb
<div style="background-color: #3399FF;">
<div class="ui very padded container">
<div style="background-color: #3399FF;">
<h1 style = "color:white">News Feed</h1>


<div class="ui raised very padded text container">
<%= form_tag tweets_path, method: :post do %>
    <%= text_area_tag :'tweet[text]' %><br>
    <%= submit_tag "Tweet" %><br><br>
<% end %>
</div>
</div>
</div>
</div>



  
  
<div class="ui grid">


<div class="right floated eight wide column">
<div class="ui raised very padded text container segment">
<div class=left>

<% if @current_user.feed.count > 0%>
    <% @current_user.feed.each do |tweet| %>
        <% if tweet.user %>
        <div class="ui segment">
        <div class="ui right aligned container"><%= link_to tweet.created_at.to_date, tweet_path(tweet) %></div>
        <%= link_to tweet.user.twitter_handle, user_path(tweet.user_id), method: :get %>
            <div class="ui clearing divider"></div>
                <p> <%= link_to tweet.text, tweet_path(tweet) %> <br></p>

            <% if tweet.like_user_ids.include?(@current_user.id)%>


            <button class="ui compact basic icon button">
            <%= link_to "❤️", like_path(tweet), method: :delete %>
            </button>
            <a class="ui basic red left pointing label">
            <%= tweet.likes.count %> 
            </a>

            


            <%else%>
            <button class="ui compact basic icon button">
            <%= link_to "🤍", likes_path(tweet), method: :post %>
            </button>
            <a class="ui basic red left pointing label">
            <%= tweet.likes.count %> 
            </a>
            <% end %>

          
                <% if @username["id"] == tweet.user.id %>
                <button class="ui compact basic icon button">
                <%= link_to  "🗑️", delete_tweet_path(tweet), method: :delete %>
                </button>
                <% end %>
                
                
                </div>
                
                
                
            <% end %>
        <% end %>
    <% else %>
        No tweets to show.
        <%= link_to "Find some people to follow.", users_path %>
    <% end %>
    </div>
    </div>
    </div>

    <div class="four wide column">
<div class="card">
<% hashtags = ["#BidenHarris", "#GEazy", "#MoneyOrPower?", "#HungerGains"] %>
<% hashtags1 = ["#TrumpOrNaw", "#Kamauled", "#Cosmopolitan", "#Love"] %>
<% hashtags2 = ["#Pringles", "#PopFlower", "#ClimbBack", "#NewMusic"] %>
<% hashtags3 = ["#CoronaDidIt", "#WeMadeIt", "#HowWeAte500CupNoodles"] %>
<h2>Whats Happening?</h2><br>
<div class="ui divider"></div>
 <h3><a href="/trends"><%=hashtags.uniq.sample%></a></h3><br><br>
 <div class="ui divider"></div>
 <h3><a href="/trends"><%=hashtags1.sample%></a></h3><br><br>
 <div class="ui divider"></div>
<h3> <a href="/trends"><%=hashtags2.sample%></a></h3><br><br>
<div class="ui divider"></div>
 <h3><a href="/trends"><%=hashtags3.sample%></a></h3><br><br>
 <div class="ui divider"></div>
</div>
</div>
    
    </div>
    </div>
    </div>

app/views/tweets/new.html.erb
<h2>Tweet</h2>
<%= form_for @tweet do |f| %>
	<ul>
		<% if @tweet.errors.any? %>
			<%= @tweet.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		<% end %>
    </ul>
    <% end %>

<%= form_for @tweet do |f| %>
    <%=f.text_field :text %><br><br>
    <%= f.submit "Tweet" %>
<% end %>

app/views/tweets/show.html.erb
<div style="background-color: #3399FF;">
<br>
</div>
<br>
<div class="ui raised very padded text container segment">
<div class=left>

    <div class="ui segment">
        <div class="ui right aligned container"><%= link_to @tweet.created_at.to_date, tweet_path(@tweet) %></div>
        <%= link_to @tweet.user.twitter_handle, user_path(@tweet.user_id), method: :get %>
            <div class="ui clearing divider"></div>
                <p> <%= link_to @tweet.text, tweet_path(@tweet) %> <br></p>

            <% if @tweet.like_user_ids.include?(@current_user.id)%>


            <button class="ui compact basic icon button">
            <%= link_to "❤️", like_path(@tweet), method: :delete %>
            </button>
            <a class="ui basic red left pointing label">
            <%= @tweet.likes.count %> 
            </a>

            


            <%else%>
            <button class="ui compact basic icon button">
            <%= link_to "🤍", likes_path(@tweet), method: :post %>
            </button>
            <a class="ui basic red left pointing label">
            <%= @tweet.likes.count %> 
            </a>
            <% end %>

          
                <% if @username["id"] == @tweet.user.id %>
                <button class="ui compact basic icon button">
                <%= link_to  "🗑️", delete_tweet_path(@tweet), method: :delete %>
                </button>
                <% end %>
                
                
                </div>
                
                
                
        

app/views/tweets/trends.html.erb
<div style="background-color: #3399FF;">
<div class="ui very padded container">
<h1 style = "color:white"> Trending </h1>
<br>
</div>
</div>
<br>
<div class="ui very padded container">
<% @tweets.each do |tweet| %>
    <%if tweet.user %>
    <div> <%= link_to tweet.user.twitter_handle, user_path(tweet.user_id) %></div>
    <%= link_to tweet.text, tweet_path(tweet) %> <br>
    <%= link_to tweet.created_at, tweet_path(tweet) %> <br>
    Likes <%= tweet.likes.count %> <br><br>
    <div class="ui clearing divider"></div>
    <% end %>
    <% end %>
    </div>

app/views/users/edit.html.erb
<div class=center>
<div style="background-color: #3399FF;">
<h2 style = "color:white"> Edit Profile </h2>
<br>
</div>
<br>
<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%=f.text_field :name %><br><br>
    <%=f.label :password %>
    <%=f.text_field :password %><br><br>
    <%=f.label :handle %>
    @<%=f.text_field :handle %><br><br>
    <%=f.label :bio %>
    <%=f.text_field :bio %><br><br>
    <%=f.label :birthday %>
    <%=f.date_field :birthday %><br><br>
    <%= f.submit  %>
<% end %>

<%= link_to 'Delete',  destroy_path(@user), method: :delete%>
</div>

app/views/users/followees.html.erb
<div style="background-color: #3399FF;">
<div class="ui very padded container">
<h1 style = "color:white"> Following </h1>
<br>
</div>
</div>
<br>
<div class="ui very padded container">
<% @user.followees.uniq.each do |followee| %>
    <b><%= link_to followee.twitter_handle, user_path(followee) %></b><br>
    <%= followee.name %><br><br>
    <% end %>
</div>

app/views/users/followers.html.erb
<h2> Followers </h2>

<% @user.followers.uniq.each do |follower| %>
    <b><%= link_to follower.twitter_handle, user_path(follower) %></b><br>
    <%= follower.name %><br><br>
    <% end %>

app/views/users/index.html.erb
<div style="background-color: #3399FF;">
<div class="ui very padded container">
<div style="background-color: #3399FF;">
<h1 style = "color:white">People to Follow</h1>
</div>
</div>
<div class="ui raised very padded text container segment">
<div class="ui middle aligned divided list">
<% @users.each do |user| %>
    <% next if user == @current_user %>
        <div class="item">
        <div> <%= link_to user.twitter_handle, user_path(user) %> </div>
         <%= user.name %>
        <% if @current_user.followees.include?(user) %>
        <div class="right floated content">
        <button class="mini ui button">
        <i class="user icon"></i>
        <%= link_to "Unfollow", unfollow_path(user), method: :delete %> <br>
        </button>
        </div>
        <% else %>
        <div class="right floated content">
        <button class="mini ui button">
        <i class="user icon"></i>
        <%= link_to "Follow", follow_path(user), method: :post %> <br>
        </button>
        </div>
        <% end %>
        </div>

<% end %>
</div>
</div>
<br><br><br><br><br>
</div>




  
    
      
    

app/views/users/new.html.erb
<h2>Create a New User Account</h2>

<%= form_for @user do |f| %>
		<% if @user.errors.any? %>
			<% @user.errors.full_messages.each do |msg| %>
                <a class="ui red basic label"><%= msg %></a><br>
            <% end %>
            <br>
		<% end %>
    <% end %>

<%= form_for @user do |f| %>
    <%=f.label :name %>
    <%=f.text_field :name %><br><br>
    <%=f.label :password %>
    <%=f.text_field :password %><br><br>
    <%=f.label :handle %>
    @<%=f.text_field :handle %><br><br>
    <%=f.label :bio %>
    <%=f.text_field :bio %><br><br>
    <%=f.label :birthday %>
    <%=f.date_field :birthday %><br><br>
    <%= f.submit "Create Your Account" %>
<% end %>

<div style="background-color: #3399FF;">
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>

app/views/users/show.html.erb
<div style="background-color: #3399FF;">
<div class="ui very padded container">
<div style = "color:white">
<h2><%= image_tag("ice.png", :size => "50x50") %>
<%= @user.name.titlecase %> <br></h2>
<% if @current_user.followees.include?(@user) %>
<button class="mini ui button">
<i class="user icon"></i>
<%= link_to "Unfollow", unfollow_path(@user), method: :delete %> <br>
</button>
<% elsif @current_user == @user %>
<%= "" %>
<% else %>
  <button class="mini ui button">
  <i class="user icon"></i>
  <%= link_to "Follow", follow_path(@user), method: :post %> <br>
  </button>
<% end %>
Followers: <%= link_to @user.followers.uniq.count, follower_path(@user)%> 
Following: <%= link_to @user.followees.uniq.count, followee_path(@user)%><br><br>
</div>
</div>
</div>
<br>
<div class="ui grid">
<div class="right floated four wide column">
<div class="ui very padded container">
<div class=left>
  
<b> <%= @user.name.titlecase %> </b><br>
<b> <%= @user.twitter_handle %> </b><br
<b> bio: <%= @user.bio %> </b><br>
<b> birthday: <%= @user.birthday %></b><br>
<br>
<% if @current_user == @user %>
<%= form_tag tweets_path, method: :post do %>
    <label>Tweet:</label><br>
    <%= text_area_tag :'tweet[text]' %><br>
    <%= submit_tag "Submit Post" %><br><br>
<% end %>
<% end %>
</div>
</div>
</div>


<div class="eight wide column">
<div class="ui very padded text container segment">
<h3> Tweets: <%= @user.tweets.count %> </h3>
<div class="ui clearing divider"></div>
    <% @user.tweets.reverse.each do |tweet| %>
      <div class="ui segment">
        <div class="ui right aligned container"><%= link_to tweet.created_at.to_date, tweet_path(tweet) %></div>
        <%= link_to tweet.user.twitter_handle, user_path(tweet.user_id), method: :get %>
            <div class="ui clearing divider"></div>
                <p> <%= link_to tweet.text, tweet_path(tweet) %> <br></p>

            <% if tweet.like_user_ids.include?(@current_user.id)%>


            <button class="ui compact basic icon button">
            <%= link_to "❤️", like_path(tweet), method: :delete %>
            </button>
            <a class="ui basic red left pointing label">
            <%= tweet.likes.count %> 
            </a>

            


            <%else%>
            <button class="ui compact basic icon button">
            <%= link_to "🤍", likes_path(tweet), method: :post %>
            </button>
            <a class="ui basic red left pointing label">
            <%= tweet.likes.count %> 
            </a>
            <% end %>

          
                <% if @username["id"] == tweet.user.id %>
                <button class="ui compact basic icon button">
                <%= link_to  "🗑️", delete_tweet_path(tweet), method: :delete %>
                </button>
                <% end %>
                
                
                </div>
                
                
                
            <% end %>

</div>
</div>
<div class="two wide column"></div>
</div>
</div>